### ISSUE TITLE
rgdal and rgeos will retire

### ISSUE THREAD

**Issue by edzer** [USDAForestService/FIESTAutils#3]
Dear maintainer(s),

as you may have noticed from the `rgdal` startup messages, or [this blog post](https://r-spatial.org/r/2022/04/12/evolution.html), or from my 2021 UseR! keynote, rgdal, rgeos and maptools will soon retire. We found out from reverse dependency checks, and looking at concrete dependencies summarized in [this table](https://r-spatial.github.io/evolution/report.html#by-depending-package) that this package heavily depends on these retiring packages, and in particular on low-level functions like `GDAL.open` that will not have obvious successors in more modern packages. Please confirm that you are aware of this, and let us know if you have particular questions.

Cc: @rsbivand

**Comment by rsbivand** [comment]
You will note that **rgdal** 1.6-2 released a month ago deprecated a number of functions and methods. **FIESTAutils** uses at least:
```
rgdal::copyDataset rgdal::GDAL.close rgdal::GDAL.open rgdal::GDALcall rgdal::GDALinfo rgdal::getDescription rgdal::getProjectionRef rgdal::getRasterBand rgdal::getRasterData rgdal::make_EPSG rgdal::project rgdal::projInfo rgdal::putRasterData rgdal::readOGR rgdal::saveDataset
```
in code. We expect to retire **rgdal** during 2023. No package uses **FIESTAutils** other than **FIESTA**, so we do not need to take extra measures to encourage you to upgrade your package or to drop it and rather use other packages directly in your workflows. We will not contact you again.

**Comment by rsbivand** [comment]
Since **terra** and **sf** do not expose low-level access to GDAL in R code, perhaps look at https://github.com/hypertidy/vapour, and work with its developer to add in anything you still need. You should take action urgently, we expect to make breaking changes in June 2023.

**Comment by rsbivand** [comment]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023. 

Fix by June, latest October 2023.

**Comment by ctoney** [comment]
Closing this upon `rgdal` retirement 2023-10-16.

@edzer, @rsbivand Thank you for the information provided here and all your work to make this a smooth transition.
